//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: gui.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef CODELITE_FFCUT_GUI_BASE_CLASSES_H
#define CODELITE_FFCUT_GUI_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/textctrl.h>
#include <wx/slider.h>
#include <wx/button.h>
#include <wx/combobox.h>
#include <wx/arrstr.h>
#include <wx/filepicker.h>
#include <wx/checklst.h>
#include <wx/spinbutt.h>
#include <wx/statusbr.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

class MainFrameBase : public wxFrame
{
protected:
    wxTextCtrl* tcLog;
    wxSlider* sdPosition;
    wxButton* btRRR;
    wxButton* btRR;
    wxButton* btR;
    wxButton* btF;
    wxButton* btFF;
    wxButton* btFFF;
    wxButton* btAddCut;
    wxButton* btRemoveCut;
    wxComboBox* cbCuts;
    wxButton* btTestCut;
    wxFilePickerCtrl* fpIn;
    wxFilePickerCtrl* fpOut;
    wxTextCtrl* tcOptions;
    wxButton* btScan;
    wxButton* btCut;
    wxCheckListBox* clStreams;
    wxSpinButton* sbStreamorder;
    wxStatusBar* sbStatus;

protected:
    virtual void OnKeyDown(wxKeyEvent& event) { event.Skip(); }
    virtual void OnSdpositionScrollChanged(wxScrollEvent& event) { event.Skip(); }
    virtual void btRRROnButtonClick(wxCommandEvent& event) { event.Skip(); }
    virtual void btRROnButtonClick(wxCommandEvent& event) { event.Skip(); }
    virtual void btROnButtonClick(wxCommandEvent& event) { event.Skip(); }
    virtual void btFOnButtonClick(wxCommandEvent& event) { event.Skip(); }
    virtual void btFFOnButtonClick(wxCommandEvent& event) { event.Skip(); }
    virtual void btFFFOnButtonClick(wxCommandEvent& event) { event.Skip(); }
    virtual void btAddCutOnButtonClick(wxCommandEvent& event) { event.Skip(); }
    virtual void btRemoveCutOnButtonClick(wxCommandEvent& event) { event.Skip(); }
    virtual void cbCutsOnCombobox(wxCommandEvent& event) { event.Skip(); }
    virtual void OnFpinFilepickerChanged(wxFileDirPickerEvent& event) { event.Skip(); }
    virtual void btScanOnButtonClick(wxCommandEvent& event) { event.Skip(); }
    virtual void btCutOnButtonClick(wxCommandEvent& event) { event.Skip(); }
    virtual void sbStreamorderOnSpin(wxSpinEvent& event) { event.Skip(); }

public:
    wxTextCtrl* GetTcLog() { return tcLog; }
    wxSlider* GetSdPosition() { return sdPosition; }
    wxButton* GetBtRRR() { return btRRR; }
    wxButton* GetBtRR() { return btRR; }
    wxButton* GetBtR() { return btR; }
    wxButton* GetBtF() { return btF; }
    wxButton* GetBtFF() { return btFF; }
    wxButton* GetBtFFF() { return btFFF; }
    wxButton* GetBtAddCut() { return btAddCut; }
    wxButton* GetBtRemoveCut() { return btRemoveCut; }
    wxComboBox* GetCbCuts() { return cbCuts; }
    wxButton* GetBtTestCut() { return btTestCut; }
    wxFilePickerCtrl* GetFpIn() { return fpIn; }
    wxFilePickerCtrl* GetFpOut() { return fpOut; }
    wxTextCtrl* GetTcOptions() { return tcOptions; }
    wxButton* GetBtScan() { return btScan; }
    wxButton* GetBtCut() { return btCut; }
    wxCheckListBox* GetClStreams() { return clStreams; }
    wxSpinButton* GetSbStreamorder() { return sbStreamorder; }
    wxStatusBar* GetSbStatus() { return sbStatus; }
    MainFrameBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("ffcut"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,500), long style = wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL);
    virtual ~MainFrameBase();
};

#endif
