/*********************************************************************
 * Name:      	main.h
 * Purpose:   	Declares simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:    
 * Created:   
 * Copyright: 
 * License:   	wxWidgets license (www.wxwidgets.org)
 * 
 * Notes:		Note that all GUI creation code is declared in
 * 				gui.h source file which is generated by wxFormBuilder.
 *********************************************************************/

#ifndef __main__
#define __main__

// main wxWidgets header file
#include <wx/wx.h>
#include <wx/numformatter.h>
// gui classes generated by wxFormBuilder
#include "gui.h"

#include <map>

extern "C" {
#include "libavformat/avformat.h"
#include "libswscale/swscale.h"
#include "libavutil/imgutils.h"

#include "SDL.h"
}


////////////////////////////////////////////////////////////////////////////////
// application class declaration 
////////////////////////////////////////////////////////////////////////////////

class MainApp : public wxApp
{
	public:
		virtual bool OnInit();
};

// declare global static function wxGetApp()
DECLARE_APP(MainApp)

////////////////////////////////////////////////////////////////////////////////
// main application frame declaration 
////////////////////////////////////////////////////////////////////////////////

class MainFrame : public MainFrameBase
{
	public:
		MainFrame( wxWindow *parent );
		virtual ~MainFrame();
		
	protected:
		AVFormatContext *fc = NULL;
		SDL_Window *window = NULL;
		SDL_Renderer *renderer = NULL;
		SDL_Texture *texture = NULL;

		wxTimeSpan previewedPTS;
		int64_t previewedPos;
		AVStream *previewedStream;

		// protected event handlers
		virtual void OnCloseFrame( wxCloseEvent& event );
		virtual void OnExitClick( wxCommandEvent& event );
		
		void OnFpinFilepickerChanged( wxFileDirPickerEvent& event );
		void btFOnButtonClick( wxCommandEvent& event );
		void btFFOnButtonClick( wxCommandEvent& event );
		void btFFFOnButtonClick( wxCommandEvent& event );
		void OnSdpositionScrollChanged( wxScrollEvent& event );
		void btRRROnButtonClick( wxCommandEvent& event );
		void btRROnButtonClick( wxCommandEvent& event );
		void btROnButtonClick( wxCommandEvent& event );
		void btScanOnButtonClick( wxCommandEvent& event );
		void btCutOnButtonClick( wxCommandEvent& event );
		void btAddCutOnButtonClick( wxCommandEvent& event );
		void btRemoveCutOnButtonClick( wxCommandEvent& event );
		void cbCutsOnCombobox(wxCommandEvent& event);
		void sbStreamorderOnSpin( wxSpinEvent& event );
		void OnKeyDown(wxKeyEvent& event);
		
		void Scan();
		void Preview();
		void Seek(int64_t bytepos, wxTimeSpan timepos);
		int NextPacket(int stream_index, AVPacket *pkt, int flags = 0);
};

#endif //__main__
